contentful/extensions

- .gitignore
- .travis.yml
- core-field-editors/.eslintrc.yml
- core-field-editors/.gitignore
- core-field-editors/README.md
- core-field-editors/bin/bundle
- core-field-editors/package.json
- core-field-editors/src/_shared/boot.js
- core-field-editors/src/_shared/input-updater.js
- core-field-editors/src/all.js
- core-field-editors/src/textarea/extension.json
- core-field-editors/src/textarea/index.js
Tests will be provided at a later point.
> Add 'textarea' core editor

- README.md
- core-field-editors/README.md
Put a line character limit as well.
> Updates in documentation to introduce core field editors

- .travis.yml
- core-field-editors/.eslintrc.yml
- core-field-editors/README.md
- core-field-editors/package.json
- core-field-editors/src/all.js
- core-field-editors/src/text-input/character-constraint.js
- core-field-editors/src/text-input/character-info.js
- core-field-editors/src/text-input/extension.json
- core-field-editors/src/text-input/framework/component.js
- core-field-editors/src/text-input/framework/extension-field-properties.js
- core-field-editors/src/text-input/framework/index.js
- core-field-editors/src/text-input/framework/input.js
- core-field-editors/src/text-input/framework/preact.js
- core-field-editors/src/text-input/framework/state.js
- core-field-editors/src/text-input/index.js
- core-field-editors/test/.eslintrc.yml
- core-field-editors/test/mocha.opts
- core-field-editors/test/support/assert/dom.js
- core-field-editors/test/support/assert/index.js
- core-field-editors/test/support/boot.js
- core-field-editors/test/support/document.js
- core-field-editors/test/support/dom.js
- core-field-editors/test/support/empty.js
- core-field-editors/test/support/extension-api-mock.js
- core-field-editors/test/support/sinon.js
- core-field-editors/test/text-input.test.js
- core-field-editors/test/textarea.test.js
Includes tests for textarea editor.
Test support modules are a bit unpolished because I don’t know yet where we are going with them. We’ll refactor when we have more tests.
> Single Line editor

- samples/README.md
- samples/alloy-editor/README.md
- samples/chessboard/README.md
- samples/diff/README.md
- samples/json-editor/README.md
- samples/json-editor/extension.prod.json
- samples/json-editor/package.json
- samples/json-form-editor/README.md
- samples/rating-dropdown/README.md
- samples/slug/README.md
- samples/translate/README.md
- samples/wistia/README.md
- samples/youtube-id/README.md
Proposing to add a set of common requirements and steps at the root of all samples to simplify each individual sample documentation.
> Fixes to documentation after repository migration

- samples/external-api/README.md
- samples/external-api/app.html
- samples/external-api/extension.json
Demonstrates exposing external API data within the Contentful UI.
> Add external API sample

- samples/diff/README.md
- samples/diff/index.html
- samples/diff/package.json
-Migrated example to new CLI
-fixed a small issue with empty published values
-simplified readme so extension management instructions are not duplicated
> Updated the diff extension.

- core-field-editors/package.json
This PR bumps the version to 1.0.0 for the NPM publish.
> Bump to 1.0.0

- samples/json-form-editor/index.html
There is a bug with the JSON Form Editor, this makes a call to get the text from the domNode. This will fix issue #78
> Get text from dom node

- .circleci/config.yml
- marketplace/Readme.md
- marketplace/google-analytics/package-lock.json
- marketplace/google-analytics/package.json
- marketplace/google-analytics/test/__snapshots__/analytics.test.js.snap
- marketplace/google-analytics/test/analytics.test.js
- Adds a readme to the marketplace folder
- Adds more tests to the Google Analytics extension
- Enable automatic deployments
> Housekeeping

- .circleci/config.yml
> Fix the deploy job on CircleCI

- marketplace/google-analytics/extension.json
- marketplace/google-analytics/src/index.js
- marketplace/google-analytics/src/timeline.js
I only noticed the name is wrong when I built the doc-app preview...
> Minor fixes for the Google Analytics extension

- marketplace/sensitive-language/.babelrc
- marketplace/sensitive-language/extension.json
- marketplace/sensitive-language/package-lock.json
- marketplace/sensitive-language/package.json
- marketplace/sensitive-language/src/app.js
- marketplace/sensitive-language/src/index.css
- marketplace/sensitive-language/src/index.html
- marketplace/sensitive-language/src/index.js
- marketplace/sensitive-language/src/language-checker.js
- marketplace/sensitive-language/src/message.js
- marketplace/sensitive-language/src/no-issues.js
- marketplace/sensitive-language/src/unsupported-language.js
- marketplace/sensitive-language/test/.eslintrc
- marketplace/sensitive-language/test/__snapshots__/app.test.js.snap
- marketplace/sensitive-language/test/__snapshots__/message.test.js.snap
- marketplace/sensitive-language/test/__snapshots__/no-issues.test.js.snap
- marketplace/sensitive-language/test/__snapshots__/unsupported-language.test.js.snap
- marketplace/sensitive-language/test/app.test.js
- marketplace/sensitive-language/test/message.test.js
- marketplace/sensitive-language/test/mock-component.js
- marketplace/sensitive-language/test/no-issues.test.js
- marketplace/sensitive-language/test/unsupported-language.test.js
Todo:
@m10l Can you help out with the 2nd point?
> Add Sensitive Language extension

- marketplace/bynder-assets/MARKETPLACE.md
- marketplace/bynder-assets/README.md
This will allow us to show more streamlined & user-focused information in the marketplace
> Add MARKETPLACE.md for Bynder extension

- marketplace/.eslintrc
- marketplace/typeform/.babelrc
- marketplace/typeform/extension.json
- marketplace/typeform/package-lock.json
- marketplace/typeform/package.json
- marketplace/typeform/src/app.js
- marketplace/typeform/src/fetch.js
- marketplace/typeform/src/index.css
- marketplace/typeform/src/index.html
- marketplace/typeform/src/index.js
- marketplace/typeform/src/warning.js
- marketplace/typeform/test/.eslintrc
- marketplace/typeform/test/__snapshots__/app.test.js.snap
- marketplace/typeform/test/__snapshots__/warning.test.js.snap
- marketplace/typeform/test/app.test.js
- marketplace/typeform/test/helpers.js
- marketplace/typeform/test/warning.test.js
> Add Typeform UI extension

- marketplace/optimizely/package-lock.json
- marketplace/optimizely/package.json
- marketplace/optimizely/test/__snapshots__/app-sidebar.spec.js.snap
- marketplace/optimizely/test/__snapshots__/app.spec.js.snap
- marketplace/optimizely/test/__snapshots__/components.spec.js.snap
- marketplace/optimizely/test/app-sidebar.spec.js
- marketplace/optimizely/test/app.spec.js
- marketplace/optimizely/test/components.spec.js
- marketplace/optimizely/test/index.spec.js
- marketplace/optimizely/test/mockProps.js
I've added unit tests to the top level components and the entry point logic. I believe further testing should be done on the `App` itself but if that should be in the unit test world is an open question. I personally think it will be easier to test at the integration level if we don't have to mock out as many things. Let me know your thoughts.
> Testing Optimizely

- marketplace/gatsby-preview/src/AppConfig.js
- marketplace/gatsby-preview/src/styles.js
Updating some styles after a round of review.
> Gatsby tweaks

- marketplace/shared-dam-app/src/Editor/SortableComponent.tsx
This makes DAM apps drag and drop really smooth, grid-base and also fixes very glitchy/blinkly firefox
> DAM apps smooth D&D

- marketplace/bynder-assets/package.json
- marketplace/bynder-assets/src/index.js
- marketplace/cloudinary-assets/package.json
- marketplace/cloudinary-assets/src/index.js
- marketplace/gatsby-preview/src/AppConfig.js
- marketplace/gatsby-preview/src/index.js
- marketplace/gatsby-preview/src/styles.js
- marketplace/netlify-build/src/app/netlify-content-types.js
- marketplace/optimizely/package.json
- marketplace/optimizely/src/AppPage/Config.js
- marketplace/optimizely/src/AppPage/ContentTypes.js
- marketplace/optimizely/src/AppPage/Projects.js
- marketplace/optimizely/src/AppPage/index.js
- marketplace/optimizely/src/index.js
- marketplace/optimizely/test/__snapshots__/AppPage.spec.js.snap
- marketplace/shared-dam-app/package-lock.json
- marketplace/shared-dam-app/package.json
- marketplace/shared-dam-app/src/AppConfig/AppConfig.spec.tsx
- marketplace/shared-dam-app/src/AppConfig/AppConfig.tsx
- marketplace/shared-dam-app/src/AppConfig/FieldSelector.tsx
- marketplace/shared-dam-app/src/index.tsx
- marketplace/shared-dam-app/src/interfaces.ts
> Align styling app location for all beta apps

- marketplace/netlify-build/src/app/netlify-config-editor.js
- marketplace/netlify-build/src/app/netlify-connection.js
Improvements suggested by Malin
> UX fixes for Netlify

- marketplace/optimizely/src/AppPage/ContentTypes.js
- marketplace/optimizely/src/AppPage/Projects.js
- marketplace/optimizely/src/AppPage/RefToolTip.js
- marketplace/optimizely/src/AppPage/index.js
- marketplace/optimizely/test/__snapshots__/AppPage.spec.js.snap
> Optimizely copy tweaks

- marketplace/cloudinary-assets/package-lock.json
- marketplace/cloudinary-assets/src/index.js
Now displays the first derived transform on the thumbnail if present
> Apply raw transform of first derived to image

- marketplace/commercelayer-sku/src/index.css
- marketplace/commercelayer-sku/src/index.html
Hi there! I'd fix the white spaces about my mistake and I improved the single view when the sku is selected.
> Improved single selection view

- samples/image-uploader/README.md
I thought this would modify all image fields, and it took a while for me to realize it had to be enabled per-field.
> Add instructions to readme.md

- samples/alloy-editor/extension.json
People tend to think that this is an extenstion / replacement for Contentful Rich Text.
> Rename to Alloy editor avoid confusion

- lib/shared-sku-app/package-lock.json
- lib/shared-sku-app/package.json
- lib/shared-sku-app/src/SkuPicker/ProductList/ProductListItem.tsx
- lib/shared-sku-app/src/SkuPicker/ProductList/__snapshots__/ProductListItem.spec.tsx.snap
- lib/shared-sku-app/src/SkuPicker/ProductList/__snapshots__/index.spec.tsx.snap
- lib/shared-sku-app/src/SkuPicker/__snapshots__/SkuPicker.spec.tsx.snap
- lib/shared-sku-app/src/SkuPicker/styles.ts
- marketplace/commercelayer-products/src/index.js
1. Inconsistent number of items per row issue fixed by removing fixed width for image wrappers.
2. Modal window height issues fixed by allowing height overflow and restraining the size of the content wrapper within the modal
> Fix CSS bugs in shared-sku picker

- lib/shared-sku-app/src/SkuPicker/ProductList/ProductListItem.tsx
- lib/shared-sku-app/src/SkuPicker/ProductList/__snapshots__/ProductListItem.spec.tsx.snap
- lib/shared-sku-app/src/SkuPicker/ProductList/__snapshots__/index.spec.tsx.snap
- lib/shared-sku-app/src/SkuPicker/__snapshots__/SkuPicker.spec.tsx.snap
- marketplace/commercelayer-products/extension.json
- marketplace/commercelayer-products/package-lock.json
- marketplace/commercelayer-products/package.json
- marketplace/commercelayer-products/src/index.js
- marketplace/commercetools-sku/src/index.js
- marketplace/shopify-sku/src/dataTransformer.js
- marketplace/shopify-sku/src/index.js
- marketplace/shopify-sku/src/productResolvers.js
**Done**
---
* Shopify now relies on internal variant IDs instead of SKUs
* Client secret removed from Commerce Layer
* CSS overflow problems fixed for all 3 ecommerce vendor apps.
> Shared SKU fixes

- marketplace/mux-video-uploader/src/deleteButton.tsx
- marketplace/mux-video-uploader/src/index.tsx
Followup from #275 
Looks like the automated build/deploy failed because these files weren't pretty enough 💅 
See:
* https://github.com/contentful/extensions/runs/413236246
* https://circleci.com/gh/contentful/extensions/955
> npm run prettier for marketplace/mux-video-uploader

- marketplace/bynder-assets/src/index.js
- marketplace/cloudinary-assets/src/index.js
- marketplace/dropbox-assets/src/index.js
- marketplace/frontify-assets/src/index.js
note: there was nothing to sanitize for Cloudinary
> Sanitize DAM apps

- README.md
Added explanation, links to launch post, Apps FAQ, Marketplace.
> Added Apps announcement & explanation

- samples/publish-confirm/src/index.js
> fix: unpublishing link with no display field
